### ISSUE TITLE
what's up with the WEBMINAL?

### ISSUE THREAD

**Issue by nikpushkarski** [Blender3D/Webminal#1]
Hi there!  That's a pity, but... Till 1st of March webminal.org didn't available (403 Forbidden).
Are you gonna fix the problem ? :)  I hope you wil, cause webminal is brilliant terminal.  Thx.

**Comment by Lakshmipathi** [comment]
@neskuchaev, Thanks for reaching us. Yes, we had a network issue and it took us sometime to debug and fix the problem.Good news is,its up and running now :D Have fun!
