### ISSUE TITLE
403 error on https://www.webminal.org/terminal/

### ISSUE THREAD

**Issue by kchaitanyach** [Blender3D/Webminal#2]
Hi team,

Please fix the 403 error on https://www.webminal.org/terminal/.

**Comment by Lakshmipathi** [comment]
I restarted the services, please check now. @kchaitanyach . Thank for the report. Please remember, we highly recommend either community.webminal.org or writing to us via email for terminal download or other site related issues.

**Comment by sofiam03** [comment]
Hi! I am having problem with 403 error in https://www.webminal.org/terminal/.

Can you fix it please?

Thank you!!

**Comment by Lakshmipathi** [comment]
Hi there. 
It looks like some strange hard disk issue. I'll look into sometime tomorrow.

**Comment by Lakshmipathi** [comment]
Its up and running now.  thanks!

**Comment by sofiam03** [comment]
Thank you so much!!
